<?php
return [
    'Thêm người dùng' => 'them-nguoi-dung',
    'Sửa người dùng' => 'sua-nguoi-dung',
    'Xóa người dùng' => 'xoa-nguoi-dung',
    'Thêm hãng xe' => 'them-hang xe',
    'Sửa hãng xe' => 'sua-hang xe',
    'Xóa hãng xe' => 'xoa-hang xe',
    'Thêm văn phòng' => 'them-van-phong',
    'Sửa văn phòng' => 'sua-van-phong',
    'Xóa văn phòng' => 'xoa-van-phong',
    'Thêm địa điểm' => 'them-dia-diem',
    'Sửa địa điểm' => 'sua-dia-diem',
    'Xóa địa điểm' => 'xoa-dia-diem',
    'Thêm tuyến đường' => 'them-tuyen-duong',
    'Sửa tuyến đường' => 'sua-tuyen-duong',
    'Xóa tuyến đường' => 'xoa-tuyen-duong',
    'Thêm chuyến' => 'them-chuyen',
    'Sửa chuyến' => 'sua-chuyen',
    'Xóa chuyến' => 'xoa-chuyen',
    'Thêm lịch chạy' => 'them-lich-chay',
    'Sửa lịch chạy' => 'sua-lich-chay',
    'Xóa lịch chạy' => 'xoa-lich-chay',
    'Thêm vé' => 'them-ve',
    'Sửa vé' => 'sua-ve',
    'Xóa vé' => 'xoa-ve',
    'Xóa vé' => 'xoa-ve',
    'Thêm quyền' => 'them-quyen',
    'Sửa quyền' => 'sua-quyen',
    'Xóa quyền' => 'xoa-quyen',
];
